### ISSUE TITLE
Нужна поддержка alias для путей

### ISSUE THREAD

**Issue by Hydrock** [alfa-laboratory/library-utils#118]
Мы активно используем библиотеку для сборки наших локальных библиотек. Очень частно файлы нашей библиотеки ссылаются друг на друга. Было бы очень удобно если бы был хотябы один alias для папки src, что бы не писать путь типа ../../utils/utils.ts ,а просто Src/utils/util.ts

**Comment by Heymdall** [comment]
Для задание алиасов можно пользоваться [path в tsconfig](https://www.typescriptlang.org/tsconfig#paths).
Единственное, для того, чтобы при этом корректно отрабатывала генерация d.ts нужно сделать ряд дополнительных телодвижений. https://github.com/alfa-laboratory/library-utils/pull/117 - в этом пр был добавлен параметр tsCompiler, который придется использовать для передачи кастомного компилятора ts.

По умолчанию ts при генерации d.ts файлов будет оставлять алиасы как есть, и при использовании либы будут возникать проблемы.
